### ISSUE TITLE
Allow selecting which SIM to use to send messages [dual-sim smartphone]

### ISSUE THREAD

**Issue by eriksson** [NdoleStudio/httpsms#130]
I have a use case where I want to select which SIM to use to send a message.
It would also be nice to be able to define the default SIM to use in a message thread, while also giving the user the ability to change per message.

I'm opening this issue to discuss the implementation.
I intend to do some contributions to implement the feature.

**Comment by AchoArnold** [comment]
Hello @eriksson 

I'm interested in the PR. I don't have a 2 sim phone so I won't be able to develop/test this. But as a pointer, I think you'll need to update the SMS manager here https://github.com/NdoleStudio/httpsms/blob/main/android/app/src/main/java/com/httpsms/SmsManagerService.kt#L35

**Comment by AchoArnold** [comment]
Fixed in https://github.com/NdoleStudio/httpsms/pull/133

**Comment by saksa1** [comment]
Hi @eriksson , @AchoArnold , I want to use this feature on my Dual SIM phone, but it only shows SIM1 as the default. Can I be allowed to select which SIM to use to send messages? Thanks to the team for this amazing product.
