### ISSUE TITLE
not showing the phone number on the dashboard, can't do the next

### ISSUE THREAD

**Issue by 9cat** [NdoleStudio/httpsms#143]
1. create the account, 
2. get the apikey,
3.  install the apk. 
4. put in the key in the app.
5. login works, sent heart beats  (huawei mate30 pro)
7. can't see the phone number on the dashboard, and also can't send message.

What did I miss?

**Comment by AchoArnold** [comment]
Hello @9cat 

Which version of the mobile app do you have? I think the phone number on the app has an issue so it's not sending the heartbeats to the server.

- Logout of the app on the mobile phone and log in again to see if it solves the issue.

**Comment by 9cat** [comment]
> Hello @9cat
> 
> Which version of the mobile app do you have? I think the phone number on the app has an issue so it's not sending the heartbeats to the server.
> 
>     * Logout of the app on the mobile phone and log in again to see if it solves the issue.


I have tried the login and logout many time.  it does not work.  

![image](https://user-images.githubusercontent.com/1379110/227091132-2eca510a-2f64-428c-8617-7ebf03955ed8.png)

**Comment by 9cat** [comment]
the phone it is huawei. mate30 pro , do not have the google service. 
the version should be "baf229a "

**Comment by AchoArnold** [comment]
Ahh I see @9cat 

I use google firebase to trigger push notifications, The application cannot work currently without google services.

**Comment by 9cat** [comment]
> Ahh I see @9cat
> 
> I use google firebase to trigger push notifications, The application cannot work currently without google services.

Great, thanks for your feedback,   I using the google service addon , now the app works~
Nice app. let dig it more with the app.
