### ISSUE TITLE
Setup Google Clould Tasks

### ISSUE THREAD

**Issue by haovd** [NdoleStudio/httpsms#149]
Hi!
I am trying to run your source code on localhost, but I am facing an error.
![Screenshot 2023-03-31 at 16 23 50](https://user-images.githubusercontent.com/42987687/229081815-793a0c09-c0b8-4fe5-8801-c7ffc91aad06.png)

I run Google Cloud Tasks on my GCP, but I don't know how to config variables on the .env file. This is my config

```
EVENTS_QUEUE_TYPE=Push
EVENTS_QUEUE_USER_API_KEY=3fe73b366f1c1d084167510c80a5d2716ed75aec
EVENTS_QUEUE_NAME=send-sms
EVENTS_QUEUE_USER_ID=106876502026290341703
EVENTS_QUEUE_ENDPOINT=projects/http-sms/locations/asia-east2/queues/send-sms
```

Can you help me?

**Comment by AchoArnold** [comment]
Hello @haovd,

You can run it on your local computer without google cloud.  in the .env file, 

`EVENTS_QUEUE_TYPE=emulator`

This will not use google cloud task, but rather it will use a local emulator.

Let me know how it goes

**Comment by haovd** [comment]
@AchoArnold Wow, I did it

Thank you so much.

**Comment by AchoArnold** [comment]
Btw 

EVENTS_QUEUE_USER_ID=106876502026290341703

This h
Should be the ID of the user with this API key 


EVENTS_QUEUE_USER_API_KEY=3fe73b366f1c1d084167510c80a5d2716ed75aec

**Comment by haovd** [comment]
Hi @AchoArnold , 

Does android app can receive firebase message on background and then send SMS?

I see it only send SMS on foreground. On background it only show notification

**Comment by AchoArnold** [comment]
Yes @haovd,

The application receives firebase notification on the background and send SMS messages. The foreground notification is there so as to prevent android OS from killing the application to save battery.

See the code here https://github.com/NdoleStudio/httpsms/blob/42c491c40871df3b87a4ec66ff9010f6ef03da11/android/app/src/main/java/com/httpsms/FirebaseMessagingService.kt#L17

**Comment by haovd** [comment]
@AchoArnold Yes, Thank you so much
