### ISSUE TITLE
Open-source the server

### ISSUE THREAD

**Issue by marcinlawnik** [NdoleStudio/httpsms#15]
Hi,

this looks amazing.

I'd like to deploy my own server, so that I don't use your resources.
Would you mind open-sourcing that?

Best regards ;)

**Comment by marcinlawnik** [comment]
Disregard, I'm dumb and didn't notice the folder. I'll do a PR with more visibility.

**Comment by AchoArnold** [comment]
Cool keep me posted @marcinlawnik 

I'll like to hear more about your use case

**Comment by marcinlawnik** [comment]
The use case is notifying users about upcoming events they signed up for so they don't miss them (opt-in, sent 36hrs before the event so they can cancel without consequences).

We already have a phone with unlimited SMS plan which is in use and costs around 50PLN per month. 

The internet sms gateways start from 0.1PLN per message. 

Right now we have about a 1000 sms to send per week (rough estimate), and it might grow, so you see the financial calculation is simple.
