### ISSUE TITLE
Integration with Wordpress plugin

### ISSUE THREAD

**Issue by toppwap** [NdoleStudio/httpsms#18]
Hello,

I am a fellow african and have been searching for an open source gateway like yours. I am happy that this one just works.
See, I am not a developer myself, so i am having a hard time figuring out how to use this api with a Wordpress plugin I use. There are some credentials i need to fill. Can you point me at the right direction.? Please have a look: https://imgur.com/nIP5U2Y

**Comment by AchoArnold** [comment]
I've not used WordPress for a very long time but I'm happy to help. Which plugin are you using to connect to the API?

**Comment by toppwap** [comment]
It is an internal plugin. The values i need are:

SMS Gateway URL
HTTP Header
Gateway Parameters

**Comment by AchoArnold** [comment]
Hey @toppwap,

Try the following values, 

SMS Gateway URL
```
https://api.httpsms.com/messages/send
```

HTTP Header

```
HeaderKey: x-api-key
HeaderValue: Get your API key from https://httpsms.com/settings/
```


Gateway Parameters
```
{
  "content": "This is a sample text message",
  "from": "+18005550199",
  "to": "+18005550100"
}
```

**Comment by toppwap** [comment]
I only get this responses:

Via get: "Cannot GET messages/send"
Via post: "Method not allowed"

**Comment by AchoArnold** [comment]
Hey @toppwap 

It should be "POST" it should be an HTTP POST request.  Also, the ContentType should be JSON.

You could try it out using the swagger playground here https://api.httpsms.com/index.html#/Messages

![image](https://user-images.githubusercontent.com/4196457/192265900-e3162e10-9ae5-4bca-8a09-2136045d6e81.png)

**Comment by AchoArnold** [comment]
Any success @toppwap?

Feel free to open the issue again if you need help
