### ISSUE TITLE
the APK don't work on my samsung A5 (2017)

### ISSUE THREAD

**Issue by inkskull** [NdoleStudio/httpsms#20]
Hello,

Your application seems very interesting. But when I'm triyng to install the APK it fails even if I'm in developper mode or using an apk installer app. I don't have any log to show. My phone works on android 8.0.0. perhaps to old?

Thanks for your help.

**Comment by AchoArnold** [comment]
Hello @inkskull 
Do you have any specific error messages? but the application is targeted for android 11, API Level 31 minimum.

**Comment by inkskull** [comment]
Was busy this morning. Tried on my wife samsung S9 under android 10. Got the same result : while downloading got a message : "file potentialy corrupted". And while installing : "A problem has occured while package analysis" and then the install process stops. Of course in the parameters I've allowed package installation from unknown sources...

**Comment by AchoArnold** [comment]
Perhaps samsung has some issue installing external APK's, Try one thing, Download the APK on a computer, send it to yourself using something like whatsapp/telegram so that the download will not be corrupted and try to install again. Try that let's see @inkskull

**Comment by michabbb** [comment]
i tested the app today with the same handy, I got an error with something like "not signed" or something. no problem, I use a newer one 😏

**Comment by AchoArnold** [comment]
I want to keep it open so I can add a signed APK in the release assets.

**Comment by AchoArnold** [comment]
I've attached a signed SDK to the release, @michabbb, @inkskull  try again let's see if it works

**Comment by michabbb** [comment]
@AchoArnold i ask a friend of mine who has an android 8 and he confirmed, that he was able to install the app now, which is great. i cannot confirm that it's working in general, but being able to install it, is a very good sign - so thanks for signing the app ! 😏

**Comment by AchoArnold** [comment]
Thanks for the feedback!

**Comment by flyvolcano** [comment]
Is it possible to build for android 5.5+? I have a redmi 4a old device running on android 7.1 and the app returns "there was a problem while parsing the package" while installation.

**Comment by AchoArnold** [comment]
I couldn't @flyvolcano  android 8.0 API level 26 was the lowest I could go without any issue, If you will like to invest time in a PR to support other android version, I'll gladly merge it.
