### ISSUE TITLE
Ability to not sync received messages to httpsms

### ISSUE THREAD

**Issue by vanoudt** [NdoleStudio/httpsms#211]
Loving the service - great job! One feature I would love is the ability to disable sharing incoming messages with HttpSMS from android. The number I use isn't exclusively for HttpSMS, and I don't want to use up my credits with personal etc messages. I would much rather have the option to only use httpsms for _outgoing_ messages. (I had looked to set up my own server because of this - but gave up on that!) 

As it stands, I'm planning to disable the app on the phone except when I plan to use the API to send messages. This, of course, gets messy!

**Comment by AchoArnold** [comment]
Thanks for the feedback @vanoudt,

I understand the pain point. I'll work on adding some king of "Settings" page on the app so you can turn ON/OFF incoming messages.

 I'll ping you when it's ready for testing hopefully next week 🤞

**Comment by AchoArnold** [comment]
Hello @vanoudt 

I added a settings page on the android APP where you can disable the incoming messages from being forwarded to the server. 
Download the latest version from here and give me feedback.  https://github.com/NdoleStudio/httpsms/releases/tag/v0.0.5

**Comment by vanoudt** [comment]
Sorry for not replying sooner; this works brilliantly! Thank you so much! :-)
