### ISSUE TITLE
Feature: SMS Poll

### ISSUE THREAD

**Issue by malys** [NdoleStudio/httpsms#225]
Hi, 
I use HTTP SMS to send sms using API. Thank you for your app.

 I combine HTTP SMS with [SMS-Poll](https://github.com/interlark/sms-poll). I think that both products are the same philosophy.
I could be great to integrate it.

Bye

**Comment by AchoArnold** [comment]
Hello @malys 

What will the integration look like from your point of view? 

The way I see it, httpsms is a base platform and you can build a polling system ontop of it i you want. 

SMS-Poll is specific to polls while httpsms can be used for whatever use case you want.

**Comment by malys** [comment]
@AchoArnold
Thank for you your quick answer.
Yes I understand your point of view. For you, it's a low level service (SMS gateway, technical solution)
To my mind, It could be a high level solution to provide services based on SMS sent from mobile device & mobile application.
ex: supporting SMS poll, SMS newsletter ...
In this case,  httpSMS could replace third party professional webservices proposing free, low cost solution using own SIM card for personal use (association, end user, ...).

Another idea, I'm not confortable to enable Incoming message.
I understand that this feature is useful but it's a huge security issue. (ex: 2FA SMS validation could be stolen).
To my mind, it could be interesting to apply "white list strategy" by default and force android user to define a list of phone numbers to synchronize and for example '*' to forward every message.
For this reason, it could be difficult to publish android apps on play store, no?
Perhaps, F-Droid is more permissive and it could help you to manage updates.

I hope that my contribution can help you.

If you want, you can contact me for testing new version.

Thanks and good luck for your next development

**Comment by AchoArnold** [comment]
> Another idea, I'm not confortable to enable Incoming message.

Right now there is a setting in the android app where you can disable incoming messages completely. Adding the "allowlist" for incoming phone numbers on the phone is a nice feature but that will mean some of the state will be on the phone and some will be on the API which introduces more complexity.

> For this reason, it could be difficult to publish android apps on play store, no?

Play Store doesn't allow these types of apps unless I add a full SMS messenger functionality to it so people can send/receive text messages on the APP I plan to do that some day in the future.

> In this case, httpSMS could replace third party professional webservices proposing free, low cost solution using own SIM card for personal use (association, end user, ...).

I get your vision. Unfortunately, that's now how I see the project at the moment but It's something to keep in mind. Thanks for your feedback.
