### ISSUE TITLE
configure api url in android app (to use custom endpoints)

### ISSUE THREAD

**Issue by michabbb** [NdoleStudio/httpsms#23]
hi there,

thanks for this great work and for making it public!! ❤️ 

I am searching for a way to forward SMS to my very own API.
if I am correct, this line of code sets the URL of the server the android app is talking to:

https://github.com/NdoleStudio/httpsms/blob/9374001de09573f16162b17b50f63dc672806e88/android/app/src/main/java/com/httpsms/HttpSmsApiService.kt#L19

is that correct ? i would like to use my webserver (PHP) to process incoming SMS.
for that it would be amazing if I could configure that URL. i am not an android developer
so changing that URL and start compiling my very first kotlin app is nothing I am really excited about 😁 

so maybe there is a chance, you could make that URL configurable in the android app but keep it as default,
so nothing changes for a regular user, but someone like me, would be able to push the information to my own server.

i would be very happy, if you would be open that idea.

thanks,
micha

**Comment by AchoArnold** [comment]
Hello @michabbb 


> if I am correct, this line of code sets the URL of the server the android app is talking to:

Yep, that's the only URL that needs to change.  It's not that difficult to compile the project. Download the "Android Studio" application and make the change to that file and that's it.

I'm not a kotlin developer too.  Before this project, I had NEVER used kotlin in my life. 

>  i would like to use my webserver (PHP) to process incoming SMS.

I could also make it such that my web server forwards the incoming SMS to your webhook endpoint. This is easier than changing the URL. Because if you change the URL then you'll have to implement all the outgoing and incoming sms logic yourself.



I'll keep this ticket open, so I can implement this in the future.

**Comment by michabbb** [comment]
thanks a lot for your quick reply. the main point is to become independent, if your server is still part of the game, my project would be dead if something on your side would be broken or you or your webserver would be unavailable, doesn´t matter what the reasons are or if you stop developing this project tomorrow 😕 in my case I only need incoming SMS, so I don´t see any problems processing the request the android app pushes to the webserver, that´s the only part I really need, a simple SMS forwarder, nothing more. 

if would be happy to donate to this project in case it helps to make that feature work very soon 😏 🍺

**Comment by AchoArnold** [comment]
I understand your use case completely, It seems like a fun weekend project. Fingers crossed you may have something on your hands by Monday 🤞

**Comment by AchoArnold** [comment]
Hello @michabbb, 

Try the latest APK, you can set your server URL when logging in. Make sure to implement the `/v1/users/me`  endpoint on your PHP server since we need this endpoint to log in the user. Documentation can be found here https://api.httpsms.com/index.html#/Users/get_users_me

**Comment by michabbb** [comment]
@AchoArnold amazing, i will test it asap and let you know 😊

**Comment by michabbb** [comment]
@AchoArnold so my server just has to response with a result like this:

```json
{
  "data": {
    "active_phone_id": "32343a19-da5e-4b1b-a767-3298a73703cb",
    "api_key": "xyz",
    "created_at": "2022-06-05T14:26:02.302718+03:00",
    "email": "name@email.com",
    "id": "WB7DRDWrJZRGbYrv2CKGkqbzvqdC",
    "updated_at": "2022-06-05T14:26:10.303278+03:00"
  },
  "message": "item created successfully",
  "status": "success"
}
```

correct ?
are any values from that response "fixed" or can I just use random data ?

**Comment by AchoArnold** [comment]
> @AchoArnold so my server just has to response with a result like this:
> 
> ```json
> {
>   "data": {
>     "active_phone_id": "32343a19-da5e-4b1b-a767-3298a73703cb",
>     "api_key": "xyz",
>     "created_at": "2022-06-05T14:26:02.302718+03:00",
>     "email": "name@email.com",
>     "id": "WB7DRDWrJZRGbYrv2CKGkqbzvqdC",
>     "updated_at": "2022-06-05T14:26:10.303278+03:00"
>   },
>   "message": "item created successfully",
>   "status": "success"
> }
> ```
> 
> correct ?
> are any values from that response "fixed" or can I just use random data ?

Yes this response wil be fine . The response is not fixed only the JSON schema. You can use what ever values you want

**Comment by michabbb** [comment]
@AchoArnold just wanted to let you know, that i was successfully able to make some tests and it seems to work. your app pushed the SMS directly to my server, amazing !! thank you so much for your work!! i really hope this project stays alive for a long time 😊

**Comment by AchoArnold** [comment]
Cool. happy it all worked out!
