### ISSUE TITLE
Specify base URL in the android app

### ISSUE THREAD

**Issue by thisjt** [NdoleStudio/httpsms#263]
Would it be possible to allow us to specify our base URL in the android app? I already have an express NodeJS app running online and I'm planning to integrate the API to that. Upon reconstructing the API requests, it seems that our base URL is `/v1`. That's fine by me, but it would be nice if I can configure this.

In the server URL input in the android app I tried specifying my own base URL by extending it from `https://example.com` to `https://example.com/smsapi` and I should expect it to do requests either in `/smsapi` or `/smsapi/v1` but in the server logs it's still doing requests in `/v1`

**Comment by AchoArnold** [comment]
Hello @thisjt 
I'll work on this when I can, In the mean time, you can work around this by editing the URL manually here https://github.com/NdoleStudio/httpsms/blob/main/android/app/src/main/java/com/httpsms/HttpSmsApiService.kt

**Comment by AchoArnold** [comment]
Hello @thisjt 

I just pushed a new version of the app with the fix, Try it out and let me know https://github.com/NdoleStudio/httpsms/releases/tag/v0.0.6
