### ISSUE TITLE
Sender ID

### ISSUE THREAD

**Issue by varavatos** [NdoleStudio/httpsms#27]
i have been searching for a way to send sms to my customers for a while. i had used like textbelt and twilio but i am not satisfied with those. and landed up here. the only problem with the HTTPSMS i am facing is the sender ID. can you tell me or implement a way which i can hide my personal number and use my business name instead of the number? and also, option to not to get a reply from the customers. i mean like an alert or something which customers cannot reply you know what i mean?

**Comment by AchoArnold** [comment]
Hello @varavatos,

> can you tell me or implement a way in which i can hide my personal number and use my business name instead of the number?

You can't do that, unfortunately. You cannot hide your phone number, When you use this app to send an SMS message, it is the same as sending an SMS message using your mobile phone. You cannot hide your phone number when sending a message with your mobile phone right? Which issues are you having with twilio? Perhaps you can try other options like Azure Communication Services https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/sms/send?tabs=windows&pivots=platform-azcli

**Comment by varavatos** [comment]
all those services send sms by a random or dedicated number.. i want send sms by Name instead of showing a number.

**Comment by AchoArnold** [comment]
Hey @varavatos, It depends on the country, Some countries don't support sending the SMS using your "Name". You can see the list of countries here https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID
