### ISSUE TITLE
Is it possible to pause the Android app?

### ISSUE THREAD

**Issue by javiermartingonzalez** [NdoleStudio/httpsms#279]
Hello, is it possible to pause the Android app?

I checked the Settings pages and disabled incoming/outcoming for both lines. But even with OFF value for that options and the app closed from multitask, there is a sticky notification saying that the server is active.

So, how can I disable it temporary (without deleting the app) to avoid draining the battery?

Thank you!

**Comment by AchoArnold** [comment]
Hello @javiermartingonzalez 
I fixed it in the latest commit, Download the latest version from https://github.com/NdoleStudio/httpsms/releases/tag/v0.0.7 and restart update the application.
Thanks
