### ISSUE TITLE
[Android] Bulk messages and validation for security reasons

### ISSUE THREAD

**Issue by malys** [NdoleStudio/httpsms#289]
Hi,
I'm sending moreless a wave of 20 SMS.
My phone is my sms gateway.

Message android app is asking my always to "allow"
![](https://forums.androidcentral.com/data/attachments/9/9369-3f0b5a5b97dd4ad686befdcabb6e5e42.jpg)

I have to validate sent for an half of sent message manually.
Is there a way to have a transparent process without manual intervention?

Thanks

**Comment by AchoArnold** [comment]
Hello @malys,

This is a functionality of the android OS itself and we can't bypass it. I recommend you update the phone with the stock android image and set the messages per minute to something like 10 under your settings https://httpsms.com/settings

<img width="442" alt="image" src="https://github.com/NdoleStudio/httpsms/assets/4196457/20d69cc6-c7fe-4c05-91ec-ed370fd1867f">

**Comment by malys** [comment]
Thanks for this information.
I use stock android image and 10 messages per minute.
I wil try to put 5.

**Comment by AchoArnold** [comment]
Let me know how it goes with 2 @malys. Which verision of android do you have? I just made a test with android 12/13 and it worked wth no errors/notifications. on the screen

**Comment by malys** [comment]
I have an old phone with android 11.

**Comment by malys** [comment]
I will also applied this solution:
https://www.xda-developers.com/change-sms-limit-android/

**Comment by AchoArnold** [comment]
Does it solve the issue @malys ?

**Comment by malys** [comment]
I will try this night. it's SMS wave day We get in touch

**Comment by malys** [comment]
it's not working. The message is appearing during the process ;(

**Comment by AchoArnold** [comment]
@malys  could you try reducing the number of SMS messages per minute to see the limit of your device? You could try with 5 sms per minute right down to 0.5 sms per minute.

Another thing may be to install the google pixel ROM https://get.pixelexperience.org/  This is a dangerous process and it can brick your device so do it if you're aware of the risks.

**Comment by malys** [comment]
I will try to reduce n SMS per minute again.  I will inform you if I find a solution.
I know this ROM.My phone works fine. I don't want to install custom roms. thanks 😊

**Comment by AchoArnold** [comment]
@malys 
Did you succeed by reducing the number of SMS messages per minute?

**Comment by malys** [comment]
This week end, I wil test it

**Comment by AchoArnold** [comment]
Any updates @malys

**Comment by malys** [comment]
with less 5 sent by minute, the message has not appeared.

**Comment by malys** [comment]
I think we can close this ticket. Tweaking app, it's possible to avoid it.
thanks a lot
