### ISSUE TITLE
Show in/outcoming call number record on web

### ISSUE THREAD

**Issue by kayjhon0** [NdoleStudio/httpsms#303]
I am running a small business using httpsms to send order info
sometime customer call back using the sms number

I hope to check call record and sms in one place

so would you please add one more column on web to show call number?

**Comment by AchoArnold** [comment]
Hello,
The application does not have the ability to read your incoming calls, at the moment, You can use a tool like phone link to see your call history on your computer https://www.microsoft.com/en-gb/windows/sync-across-your-devices?r=1
