### ISSUE TITLE
Found an error to start api project

### ISSUE THREAD

**Issue by Alkiyogoma** [NdoleStudio/httpsms#32]
main.go:6:2: no required module provides package github.com/NdoleStudio/httpsms/docs; to add it:
        go get github.com/NdoleStudio/httpsms/docs

**when I run** go get github.com/NdoleStudio/httpsms/docs
**error** go: github.com/NdoleStudio/httpsms/docs: no matching versions for query "upgrade"
![Run go failed](https://user-images.githubusercontent.com/50145104/204544472-86820089-6f51-4065-820a-a44c81cb11f3.png)

go: github.com/NdoleStudio/httpsms/docs: no matching versions for query "upgrade"

**Comment by AchoArnold** [comment]
Hello @Alkiyogoma 

Sorry it's not very obvious, to generate the `docs` package install `swag` https://github.com/swaggo/swag

and then run the following command inside the `api` folder
```bash
swag init
```

This will generate the swagger documentation inside the `docs` folder.

**Comment by Alkiyogoma** [comment]
Thanks @AchoArnold 

I will do it.

**Comment by AchoArnold** [comment]
Keep me posted if you succeed @Alkiyogoma

**Comment by Alkiyogoma** [comment]
Hello @AchoArnold, Thanks It worked.

first, i cleared all cache

`go clean --modcache`

`go get github.com/swaggo/http-swagger `

`go get github.com/swaggo/swag/cmd/swag`

`swag init`

**Comment by Alkiyogoma** [comment]
sorry, I'm still new on Goland, where I run 

` go run main.go`

**ERROR** - 2022/12/02 08:34:30 Fatal: cannot load .env file: Can't separate key from value exit status 1

**current error**  I tried to copy **.env.production** to **.env** still experiencing the same error

**Comment by AchoArnold** [comment]
Hello @Alkiyogoma to make it work completely, you'll need to set the correct values in the `.env.production` file. You'll need a firebase account and a cockrochDB databse account.

**Comment by Alkiyogoma** [comment]
Thanks, It worked. Once again thanks for your help
