### ISSUE TITLE
Make it more data protection friendly (e.g. GDPR)

### ISSUE THREAD

**Issue by kapsiR** [NdoleStudio/httpsms#322]
Since the server stores everything forever, it would be really cool to have options to configure this. (e.g. never store anything after it has been sent)

> The server stores phone numbers and messages for ever at the moment. I plan to limit it to maybe 1 year or 6 months in the future when my database bacomes very large.

Source: https://twitter.com/acho_arnold/status/1727904652841168980

**Comment by AchoArnold** [comment]
You can call the delete API to delete everything you want from the server

Threads : [https://api.httpsms.com/index.html#/MessageThreads/delete_message_threads__messageThreadID_](https://api.httpsms.com/index.html#/MessageThreads/delete_message_threads__messageThreadID_)
Messages : [https://api.httpsms.com/index.html#/Messages/delete_messages__messageID_](https://api.httpsms.com/index.html#/Messages/delete_messages__messageID_)

**Comment by AchoArnold** [comment]
You can call the delete API to delete everything you want from the server

Threads : [https://api.httpsms.com/index.html#/MessageThreads/delete_message_threads__messageThreadID_](https://api.httpsms.com/index.html#/MessageThreads/delete_message_threads__messageThreadID_)
Messages: [https://api.httpsms.com/index.html#/Messages/delete_messages__messageID_](https://api.httpsms.com/index.html#/Messages/delete_messages__messageID_)
