### ISSUE TITLE
Character Limit

### ISSUE THREAD

**Issue by huddy72** [NdoleStudio/httpsms#34]
Hi,

Is there a character limit?  I get a "GENERIC_ERROR" when sending more than 160 characters.

Is there a way to increase the number of characters and send info over two texts?

Andy

**Comment by AchoArnold** [comment]
Hello, 

I think the character limit is from the handset, I have sent 2 texts and it works fine from my end, Perhaps the block is from your telco provider? See if you can send  large text SMS  on your mobile phone directly.

**Comment by AchoArnold** [comment]
I'll look into it.

**Comment by AchoArnold** [comment]
Hello @huddy72 
I fixed it in the latest update, Download the latest version of the application and try again.

**Comment by huddy72** [comment]
Looks good.  Thank you.
