### ISSUE TITLE
Notify users when a new android app is available.

### ISSUE THREAD

**Issue by AchoArnold** [NdoleStudio/httpsms#38]

**Comment by REDAL** [comment]
hi @AchoArnold 
I did downloaded the app , but it does not work , and when trying to compile it also not working ?

**Comment by AchoArnold** [comment]
Which error message do you get when you open the app? 

Also which version of Android is in your phone

**Comment by REDAL** [comment]
no I am not talking about the app it self, I saw that you said it's open source, and I did downloaded it, and opened it in Android studio, but it doesn't work

**Comment by AchoArnold** [comment]
Hello @REDAL,
When you say `"It doesn't work"` I can't debug based on that statement. Which exact error message do you get so I can debug based on the error? I do have android studio and I compiled the latest version on android studio a few days ago without any errors.

**Comment by REDAL** [comment]
@AchoArnold 
Hi, thank you for your reply, yes sure, this is a screenshot of the IDE with the error, then trying to compile it, can't even load the emulator with.


![image](https://user-images.githubusercontent.com/7544360/209163797-49398cb2-a5cb-47d3-a4a5-aa5ee527e290.png)

**Comment by AchoArnold** [comment]
@REDAL  The error looks related to `git`. What happens when you run `git rev-parse --short HEAD` from your command line.  Do you get an error? 

Did you download the repository with `git clone`?

![image](https://user-images.githubusercontent.com/4196457/209164978-89837932-043b-49ad-8d0a-b0482148eaa9.png)

**Comment by AchoArnold** [comment]
Ahh I see, it expects a  git repo. Perhaps create a new GitHub issue and i'll try to refactor it so it works without git.

**Comment by REDAL** [comment]
I appreciate your help @AchoArnold 
by the way, can we change the API endpoint or not ?
will be easier in the future to do so ?

regards

**Comment by AchoArnold** [comment]
Yes @REDAL  You can change the API endpoint on the app. See #23

**Comment by REDAL** [comment]
Hi Arnold. Thank you for your help. I really appreciate it.

Last time you told me that you would recommend pile the project so I can download it as a zip file and open it in Android Studio. Did you do that?

I have read the thread about changing the URL and point. I think it's an interesting project. Thank you again.

When you upload the new project structure, please send me a dm.

Kindest regards
________________________________

**Comment by REDAL** [comment]
By the way, did the app support ussd codes?
________________________________

**Comment by AchoArnold** [comment]
No it doesn't support USSD codes

**Comment by AchoArnold** [comment]
> Last time you told me that you would recommend pile the project so I can download it as a zip file and open it in Android Studio. Did you do that?

I've not. I'll create a new issue for that

**Comment by REDAL** [comment]
Thanks bro
________________________________

**Comment by AchoArnold** [comment]
Sendgrid mailing list setup #54257185a4297866323509fd8a7cc5547ccaedff
