### ISSUE TITLE
Improve setup instructions.

### ISSUE THREAD

**Issue by AchoArnold** [NdoleStudio/httpsms#42]
Improve instructions on how to set up the project in a local environment.

- [x] Consider adding instructions on how to build/run the project with docker-compose.
- [x] Add instructions on how to setup the project on GCP #240
- [x] Add button to run on google cloud e.g https://github.com/gofiber/recipes/tree/master/gcloud

**Comment by Shy** [comment]
Open to PRs on this one? I've been kinda hacking my way to get things up and working. Would be happy to fix.

**Comment by AchoArnold** [comment]
Yes I'm open please don't hesitate to send the PR @Shy

**Comment by pranaycb** [comment]
Can you please add php backend (api) support? Or any documentation how to replace the backend with php? Thanks for your contribution by the way

**Comment by AchoArnold** [comment]
Hello @pranaycb 
I don't plan to provide any PHP backend support.
