### ISSUE TITLE
Failure to recognize incoming messages after API key rotation and phone swap

### ISSUE THREAD

**Issue by AgentSanchez** [NdoleStudio/httpsms#433]
After rotating keys (Thanks for adding that feature), I changed the device the sim card is on, and now I am not seeing any incoming messages when I send tests to the phone line. I can send out through the httpSMS website, but no incoming messages are registered there.

- I attempted to rotate the key once more
- I cleared out all my phone numbers from the settings page on the httpSMS site.
- I cleared out all my existing threads on the httpSMS site.
- I then reset the phone application and put in the new key and it registers successfully.
- When the phone receives a message, the httpSMS does not seem to register it. It does not create a new thread, and does not send a webhook event.

I've also enabled logging in the app, but I am not sure where to retrieve the logs.

![Screenshot from 2024-05-11 16-38-24](https://github.com/NdoleStudio/httpsms/assets/37169160/f045cc05-9c8f-40ce-88fe-48f940df13e2)

**Comment by AchoArnold** [comment]
Hello @AgentSanchez  
Did you enable incoming SMS messages on the app settings page on the mobile app?

Thanks

**Comment by AgentSanchez** [comment]
Hi @AchoArnold!
Yes it is on
![d2f280c6-a7d7-45ba-9d47-1651e3b80b98](https://github.com/NdoleStudio/httpsms/assets/37169160/996ddcdf-e1e9-4dc5-ab2c-8c5c568f8b96)

**Comment by AchoArnold** [comment]
Uninstall the app and install it again then shoot me an email at arnold@httpsms.com and I'll help you debug the issue with your account. I just followed the steps you mentioned but I can't reproduce the issue.

**Comment by AgentSanchez** [comment]
I've done the steps requested. An interesting note, after cleaning data and uninstalling, upon reinstalling it auto registers to the server without inputting an API key...Is this intended behavior? I'll email you shortly.

**Comment by AchoArnold** [comment]
Continuing this via email.
