### ISSUE TITLE
iOS too ?

### ISSUE THREAD

**Issue by gedw99** [NdoleStudio/httpsms#436]
Is there any technical reason iOS can’t be done ?

**Comment by AchoArnold** [comment]
Yes you can't have custom SMS applications on iOS @gedw99

**Comment by gedw99** [comment]
sounds like an URL Schema security thing.

There must be an API for an App installed on an IOT device to create an SMS via iMessage

https://github.com/golift/imessage seems to be one.

**Comment by gedw99** [comment]
https://github.com/davidnewhall/motifini seems better and has HTTP API

**Comment by AchoArnold** [comment]
@gedw99  All the examples you mentioned are not IOS based. This are applications for your macbook. MAC OS

**Comment by gedw99** [comment]
your right.. sorry
