### ISSUE TITLE
Your client does not have permission to get URL /v1/messages/send from this server.

### ISSUE THREAD

**Issue by vanoudt** [NdoleStudio/httpsms#437]
Hello! 

I have a recent issue that has cropped up - sms messages simply aren't getting through, and it seems like I've been rejected from the server! I get a google response saying: <p>Your client does not have permission to get URL <code>/v1/messages/send</code> from this server.  <ins>That’s all we know.</ins>

**Comment by vanoudt** [comment]
Interestingly, it only seems to have locked out the server on which I run our church system... it still works fine from my local machine... Is it possible that my ip has been blocked somehow?

**Comment by AchoArnold** [comment]
Send me an email with the IP address if your church server and I'll look into it if it's blocked.

Thanks
