### ISSUE TITLE
First install of app has user issues

### ISSUE THREAD

**Issue by alban-ameti** [NdoleStudio/httpsms#562]
1) The app doesn't allow for dismiss of keyboard when finished filling fields hiding button below. Had to install a non default keyboard to get it to dismiss.

2) There is a QR code generated on the web to register the app but in the app there seems to be no way to scan that code to register and instead api key has to be filled out.

**Comment by AchoArnold** [comment]
Thanks for the feedback @alban-ameti 

I've made some updates, Download and try the latest version of the app

![image](https://github.com/user-attachments/assets/8f4bc333-d49c-4fb8-bc36-e214b981426a)
