### ISSUE TITLE
Cannot make events tasks work on GCP

### ISSUE THREAD

**Issue by fullbright** [NdoleStudio/httpsms#585]
Hello,

First of all, thanks for the amazing work with the HttpSMS app.

I have deployed the HttpSMS app on GCP.

Here is my environment variables values (I redacted some parts)

Attempt 1:
EVENTS_QUEUE_TYPE=emulator
EVENTS_QUEUE_NAME=events-local
EVENTS_QUEUE_ENDPOINT=http://localhost:8000/v1/events

Attempt 2:
EVENTS_QUEUE_TYPE=gcp_tasks
EVENTS_QUEUE_NAME=<my google cloud tasks queue name here>
EVENTS_QUEUE_ENDPOINT=projects/[PROJECT_ID]/locations/[LOCATION_ID]/queues/send-sms

Attempt 3:
EVENTS_QUEUE_TYPE=gcp_tasks
EVENTS_QUEUE_NAME=<my google cloud tasks queue name here>
EVENTS_QUEUE_ENDPOINT=https://cloudtasks.googleapis.com/v2/projects/<my gcp project id>/locations/europe-west1/queues/<my google cloud queue name>

When I try to send a message, I get this error message:

```
cannot send http request to [http://0.0.0.0:8000/v1/events] for queue task [85e47423-4418-4e2d-8de7-cfcef65a434b]
 --- at /http-sms/pkg/services/emulator_push_queue.go:77 (emulatorPushQueue.Enqueue.(*emulatorPushQueue).push.func1) ---
Caused by: ErrTransport: Post "http://0.0.0.0:8000/v1/events": POST http://0.0.0.0:8000/v1/events giving up after 1 attempt(s): context deadline exceeded
```

What I tried:

- use the emulator = gives me an error saying that the http://localhost:8000/v1/events is not reachable
- use the projects/[PROJECT_ID]/locations/[LOCATION_ID]/queues/send-sms = also get an error. I think it is because the url is not valid.
- try to read the go code to understand better but difficult since I am not a go developer.

how can I setup the queue?

let me know if you need more input.

**Comment by AchoArnold** [comment]
```.env
EVENTS_QUEUE_NAME=projects/[PROJECT_ID]/locations/[LOCATION_ID]/queues/send-sms
EVENTS_QUEUE_ENDPOINT=https://example.com/v1/events
```

The URL `https://example.com/v1/events` has to be accessible from the internet.

You can remove the `EVENTS_QUEUE_TYPE=gcp_tasks` env variable.

See https://github.com/NdoleStudio/httpsms/blob/be58689d8fd0f9a106bb1f2c5cadf05c13853e89/api/pkg/di/container.go#L425C1-L434C1
