### ISSUE TITLE
C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

### ISSUE THREAD

**Issue by mesibug** [NdoleStudio/httpsms#67]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.httpsms.com/v1/messages/send` resulted in a `422 Unprocessable Entity` response: {"data":{"content":["The content field must be maximum 1024 char"]},"message":"validation errors while sending message", (truncated...) in C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\guzzle\src\Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\promises\src\Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Prom in C:\xampp\htdocs\bulkemail\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by AchoArnold** [comment]
What's the question @mesibug ?

```
{"data":{"content":["The content field must be maximum 1024 char"]},
```

From the error message you're getting this error because the content field is longer than 1024 characters.
