### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by ChanTerelLy** [NdoleStudio/httpsms#68]
Could you, please, provide the example of the environment variables for API? It's not so obviouse about EVENTS_* variables. Is GCP_PROJECT_ID necessarily, should it work outside of GCP? What is format of FIREBASE_CREDENTIALS?

**Comment by AchoArnold** [comment]
Hello @ChanTerelLy
Currently, the project is set up to work with GCP.  You can get the environment variables from this [.env.production](https://github.com/NdoleStudio/httpsms/blob/main/api/.env.production) file 

The FIREBASE_CREDENTIALS should be a JSON string you can get it from this documentation https://firebase.google.com/docs/admin/setup

Btw, I plan to update the local setup instructions in #42
